name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Setup DynamoDB Local
        run: docker run -d -p 8000:8000 --name dynamodb-local amazon/dynamodb-local

      - name: List running Docker containers
        run: docker ps

      - name: Wait for DynamoDB to boot up
        run: node .github/workflows/wait-for-Dynamodb.js

      - name: List running Docker containers
        run: docker ps

      # - name: Create DynamoDB Tables
      #   run: node ./test/dynamoDBMigrate.js

      - name: Print DynamoDB Local logs
        run: docker logs dynamodb-local

      - name: Run tests
        run: npm test
