name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v2.0.1
        with:
          dbPath: './dynamodb-local'
          sharedDb: true
          port: 8000
          cors: '*'

      - name: Create DynamoDB Tables
        run: node ./test/dynamoDBMigrate.js

      - name: Run tests
        run: npm test
