name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Setup and start DynamoDB Local
        run: docker run -d -p 8000:8000 --name dynamodb-local amazon/dynamodb-local

      - name: Wait for DynamoDB to come to up state
        run: node .github/workflows/wait-for-Dynamodb.js

      - name: Set AWS Test environment variables
        run: |
          echo "AWS_ACCESS_KEY_ID=fakeAccessKeyId" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey" >> $GITHUB_ENV
          echo "AWS_REGION=ap-south-1" >> $GITHUB_ENV

      - name: Create Mock DynamoDB Data
        run: node ./test/dynamoDBMigrate.js

      - name: Run tests
        run: npm test
